# Air config for custom main.go 

[build]
# pre_cmd = ["make air-refresh"]
# cmd = "templ generate"
cmd = "go build -o ./tmp/main"
bin = "./tmp/main"
delay = 1000 
exclude_dir = ["tmp", "vendor", "node_modules", "dist"] 
exclude_regex = [".*_templ.go"] 
include_ext = ["go", "tpl", "tmpl", "html", "templ"] 
kill_delay = 500 # nanosecond
log = "build.log" 
send_interrupt = false 
stop_on_error = true 

[color]
build = "green"
main = "yellow"
runner = "magenta"
watcher = "cyan"

[log]
time = true
